language: generic
env:
  global:
  # Set defaults to avoid repeating in most cases
  - PYTHON_VERSION=$TRAVIS_PYTHON_VERSION
  - NUMPY_VERSION=stable
  - MAIN_CMD='python setup.py'
  # 'krb5' is added as a workaround for an issue with gdal
  # see: https://github.com/conda-forge/gdal-feedstock/issues/205
  - CONDA_DEPENDENCIES='xarray dask toolz Cython sphinx cartopy matplotlib pyproj coveralls coverage codecov gdal rasterio flake8 pytest'
  - PIP_DEPENDENCIES=''
  - SETUP_XVFB=False
  - EVENT_TYPE='push pull_request'
  - SETUP_CMD='test'
  - CONDA_CHANNELS='conda-forge'
matrix:
  include:
  - env: PYTHON_VERSION=3.6
    os: linux
  - env: PYTHON_VERSION=3.6
    os: osx
cache:
  directories:
  - $HOME/.cache/pip
  - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853
install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- pip install .
script:
- coverage run -m pytest  # Run the tests and check for test coverage.
- coverage report -m  # Generate test coverage report.
- codecov  # Upload the report to codecov.
- flake8 --max-line-length=115 geoxarray # Enforce code style (but relax line length limit a bit).
- make -C docs html  # Build the documentation.
after_success:
- if [[ $PYTHON_VERSION == 3.6 ]]; then coveralls; codecov; fi
deploy:
  - provider: pypi
    user: dhoese
    password:
      secure:
    distributions: sdist bdist_wheel
    skip_existing: true
    on:
      tags: true
      repo: geoxarray/geoxarray
